console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '{{"\n"}}❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if .WSL }}WSL at {{ end }} {{.Icon}} '
    foreground = 'p:white'
    background = 'transparent'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      linux = ' '

  [[blocks.segments]]
    template = '{{ path .Path .Location }}'
    foreground = 'p:blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:green'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:green{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = ' {{ if gt .Code 0 }}{{.Code}} {{ else }}{{ end }} '
    foreground = 'p:white'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .FormattedMs }} '
    foreground = 'p:green'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

  [[blocks.segments]]
    template = ' '
    foreground = 'p:green'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:blue'
    background = 'transparent'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    template = '<p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
    foreground = 'p:white'
    background = 'transparent'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:white'
  background = 'p:orange'
  type = 'aws'
  style = 'diamond'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  style = 'diamond'
  tips = ['az']

  [tooltips.properties]
    display_default = true
